/**
 * This class is generated by jOOQ
 */
package org.yesworkflow.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.yesworkflow.db.jooq.tables.Channel;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChannelRecord extends UpdatableRecordImpl<ChannelRecord> implements Record6<Integer, Integer, Integer, Integer, Boolean, Boolean> {

	private static final long serialVersionUID = -1888359145;

	/**
	 * Setter for <code>channel.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>channel.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>channel.data_id</code>.
	 */
	public void setDataId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>channel.data_id</code>.
	 */
	public Integer getDataId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>channel.out_port_id</code>.
	 */
	public void setOutPortId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>channel.out_port_id</code>.
	 */
	public Integer getOutPortId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>channel.in_port_id</code>.
	 */
	public void setInPortId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>channel.in_port_id</code>.
	 */
	public Integer getInPortId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>channel.is_inflow</code>.
	 */
	public void setIsInflow(Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>channel.is_inflow</code>.
	 */
	public Boolean getIsInflow() {
		return (Boolean) getValue(4);
	}

	/**
	 * Setter for <code>channel.is_outflow</code>.
	 */
	public void setIsOutflow(Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>channel.is_outflow</code>.
	 */
	public Boolean getIsOutflow() {
		return (Boolean) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Boolean, Boolean> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Boolean, Boolean> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Channel.CHANNEL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Channel.CHANNEL.DATA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Channel.CHANNEL.OUT_PORT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Channel.CHANNEL.IN_PORT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field5() {
		return Channel.CHANNEL.IS_INFLOW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field6() {
		return Channel.CHANNEL.IS_OUTFLOW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getDataId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getOutPortId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getInPortId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value5() {
		return getIsInflow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value6() {
		return getIsOutflow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChannelRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChannelRecord value2(Integer value) {
		setDataId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChannelRecord value3(Integer value) {
		setOutPortId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChannelRecord value4(Integer value) {
		setInPortId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChannelRecord value5(Boolean value) {
		setIsInflow(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChannelRecord value6(Boolean value) {
		setIsOutflow(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChannelRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Boolean value5, Boolean value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ChannelRecord
	 */
	public ChannelRecord() {
		super(Channel.CHANNEL);
	}

	/**
	 * Create a detached, initialised ChannelRecord
	 */
	public ChannelRecord(Integer id, Integer dataId, Integer outPortId, Integer inPortId, Boolean isInflow, Boolean isOutflow) {
		super(Channel.CHANNEL);

		setValue(0, id);
		setValue(1, dataId);
		setValue(2, outPortId);
		setValue(3, inPortId);
		setValue(4, isInflow);
		setValue(5, isOutflow);
	}
}
