/**
 * This class is generated by jOOQ
 */
package org.yesworkflow.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;
import org.yesworkflow.db.jooq.tables.DataResource;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataResourceRecord extends TableRecordImpl<DataResourceRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = 1178859242;

	/**
	 * Setter for <code>data_resource.data_id</code>.
	 */
	public void setDataId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>data_resource.data_id</code>.
	 */
	public Integer getDataId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>data_resource.resource_id</code>.
	 */
	public void setResourceId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>data_resource.resource_id</code>.
	 */
	public Integer getResourceId() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return DataResource.DATA_RESOURCE.DATA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return DataResource.DATA_RESOURCE.RESOURCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getDataId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getResourceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DataResourceRecord value1(Integer value) {
		setDataId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DataResourceRecord value2(Integer value) {
		setResourceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DataResourceRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DataResourceRecord
	 */
	public DataResourceRecord() {
		super(DataResource.DATA_RESOURCE);
	}

	/**
	 * Create a detached, initialised DataResourceRecord
	 */
	public DataResourceRecord(Integer dataId, Integer resourceId) {
		super(DataResource.DATA_RESOURCE);

		setValue(0, dataId);
		setValue(1, resourceId);
	}
}
