/**
 * This class is generated by jOOQ
 */
package org.yesworkflow.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.yesworkflow.db.jooq.tables.Port;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortRecord extends UpdatableRecordImpl<PortRecord> implements Record10<Integer, Integer, Integer, Integer, String, String, String, String, Boolean, Boolean> {

	private static final long serialVersionUID = -1619131251;

	/**
	 * Setter for <code>port.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>port.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>port.annotation_id</code>.
	 */
	public void setAnnotationId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>port.annotation_id</code>.
	 */
	public Integer getAnnotationId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>port.program_id</code>.
	 */
	public void setProgramId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>port.program_id</code>.
	 */
	public Integer getProgramId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>port.data_id</code>.
	 */
	public void setDataId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>port.data_id</code>.
	 */
	public Integer getDataId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>port.name</code>.
	 */
	public void setName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>port.name</code>.
	 */
	public String getName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>port.qualified_name</code>.
	 */
	public void setQualifiedName(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>port.qualified_name</code>.
	 */
	public String getQualifiedName() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>port.alias</code>.
	 */
	public void setAlias(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>port.alias</code>.
	 */
	public String getAlias() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>port.uri_template</code>.
	 */
	public void setUriTemplate(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>port.uri_template</code>.
	 */
	public String getUriTemplate() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>port.is_inport</code>.
	 */
	public void setIsInport(Boolean value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>port.is_inport</code>.
	 */
	public Boolean getIsInport() {
		return (Boolean) getValue(8);
	}

	/**
	 * Setter for <code>port.is_outport</code>.
	 */
	public void setIsOutport(Boolean value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>port.is_outport</code>.
	 */
	public Boolean getIsOutport() {
		return (Boolean) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, Integer, Integer, String, String, String, String, Boolean, Boolean> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, Integer, Integer, String, String, String, String, Boolean, Boolean> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Port.PORT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Port.PORT.ANNOTATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Port.PORT.PROGRAM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Port.PORT.DATA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Port.PORT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Port.PORT.QUALIFIED_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Port.PORT.ALIAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Port.PORT.URI_TEMPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field9() {
		return Port.PORT.IS_INPORT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field10() {
		return Port.PORT.IS_OUTPORT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getAnnotationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getProgramId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getDataId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getQualifiedName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getAlias();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getUriTemplate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value9() {
		return getIsInport();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value10() {
		return getIsOutport();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortRecord value2(Integer value) {
		setAnnotationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortRecord value3(Integer value) {
		setProgramId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortRecord value4(Integer value) {
		setDataId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortRecord value5(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortRecord value6(String value) {
		setQualifiedName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortRecord value7(String value) {
		setAlias(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortRecord value8(String value) {
		setUriTemplate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortRecord value9(Boolean value) {
		setIsInport(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortRecord value10(Boolean value) {
		setIsOutport(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, Boolean value9, Boolean value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PortRecord
	 */
	public PortRecord() {
		super(Port.PORT);
	}

	/**
	 * Create a detached, initialised PortRecord
	 */
	public PortRecord(Integer id, Integer annotationId, Integer programId, Integer dataId, String name, String qualifiedName, String alias, String uriTemplate, Boolean isInport, Boolean isOutport) {
		super(Port.PORT);

		setValue(0, id);
		setValue(1, annotationId);
		setValue(2, programId);
		setValue(3, dataId);
		setValue(4, name);
		setValue(5, qualifiedName);
		setValue(6, alias);
		setValue(7, uriTemplate);
		setValue(8, isInport);
		setValue(9, isOutport);
	}
}
