/**
 * This class is generated by jOOQ
 */
package org.yesworkflow.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.yesworkflow.db.jooq.tables.Program;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramRecord extends UpdatableRecordImpl<ProgramRecord> implements Record8<Integer, Integer, Integer, Integer, String, String, Boolean, Boolean> {

	private static final long serialVersionUID = 424535046;

	/**
	 * Setter for <code>program.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>program.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>program.parent_id</code>.
	 */
	public void setParentId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>program.parent_id</code>.
	 */
	public Integer getParentId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>program.begin_id</code>.
	 */
	public void setBeginId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>program.begin_id</code>.
	 */
	public Integer getBeginId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>program.end_id</code>.
	 */
	public void setEndId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>program.end_id</code>.
	 */
	public Integer getEndId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>program.name</code>.
	 */
	public void setName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>program.name</code>.
	 */
	public String getName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>program.qualified_name</code>.
	 */
	public void setQualifiedName(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>program.qualified_name</code>.
	 */
	public String getQualifiedName() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>program.is_workflow</code>.
	 */
	public void setIsWorkflow(Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>program.is_workflow</code>.
	 */
	public Boolean getIsWorkflow() {
		return (Boolean) getValue(6);
	}

	/**
	 * Setter for <code>program.is_function</code>.
	 */
	public void setIsFunction(Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>program.is_function</code>.
	 */
	public Boolean getIsFunction() {
		return (Boolean) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, Integer, String, String, Boolean, Boolean> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, Integer, String, String, Boolean, Boolean> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Program.PROGRAM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Program.PROGRAM.PARENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Program.PROGRAM.BEGIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Program.PROGRAM.END_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Program.PROGRAM.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Program.PROGRAM.QUALIFIED_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field7() {
		return Program.PROGRAM.IS_WORKFLOW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field8() {
		return Program.PROGRAM.IS_FUNCTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getParentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getBeginId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getEndId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getQualifiedName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value7() {
		return getIsWorkflow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value8() {
		return getIsFunction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value2(Integer value) {
		setParentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value3(Integer value) {
		setBeginId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value4(Integer value) {
		setEndId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value5(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value6(String value) {
		setQualifiedName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value7(Boolean value) {
		setIsWorkflow(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord value8(Boolean value) {
		setIsFunction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProgramRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, Boolean value7, Boolean value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProgramRecord
	 */
	public ProgramRecord() {
		super(Program.PROGRAM);
	}

	/**
	 * Create a detached, initialised ProgramRecord
	 */
	public ProgramRecord(Integer id, Integer parentId, Integer beginId, Integer endId, String name, String qualifiedName, Boolean isWorkflow, Boolean isFunction) {
		super(Program.PROGRAM);

		setValue(0, id);
		setValue(1, parentId);
		setValue(2, beginId);
		setValue(3, endId);
		setValue(4, name);
		setValue(5, qualifiedName);
		setValue(6, isWorkflow);
		setValue(7, isFunction);
	}
}
