/**
 * This class is generated by jOOQ
 */
package org.yesworkflow.db.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import org.yesworkflow.db.jooq.tables.UriVariableValue;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UriVariableValueRecord extends TableRecordImpl<UriVariableValueRecord> implements Record3<Integer, Integer, String> {

	private static final long serialVersionUID = 1749609517;

	/**
	 * Setter for <code>uri_variable_value.resource_id</code>.
	 */
	public void setResourceId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>uri_variable_value.resource_id</code>.
	 */
	public Integer getResourceId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>uri_variable_value.uri_variable_id</code>.
	 */
	public void setUriVariableId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>uri_variable_value.uri_variable_id</code>.
	 */
	public Integer getUriVariableId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>uri_variable_value.value</code>.
	 */
	public void setValue(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>uri_variable_value.value</code>.
	 */
	public String getValue() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return UriVariableValue.URI_VARIABLE_VALUE.RESOURCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return UriVariableValue.URI_VARIABLE_VALUE.URI_VARIABLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return UriVariableValue.URI_VARIABLE_VALUE.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getResourceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getUriVariableId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UriVariableValueRecord value1(Integer value) {
		setResourceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UriVariableValueRecord value2(Integer value) {
		setUriVariableId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UriVariableValueRecord value3(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UriVariableValueRecord values(Integer value1, Integer value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UriVariableValueRecord
	 */
	public UriVariableValueRecord() {
		super(UriVariableValue.URI_VARIABLE_VALUE);
	}

	/**
	 * Create a detached, initialised UriVariableValueRecord
	 */
	public UriVariableValueRecord(Integer resourceId, Integer uriVariableId, String value) {
		super(UriVariableValue.URI_VARIABLE_VALUE);

		setValue(0, resourceId);
		setValue(1, uriVariableId);
		setValue(2, value);
	}
}
