/**
 * This class is generated by jOOQ
 */
package org.yesworkflow.db.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.yesworkflow.db.jooq.tables.Annotation;
import org.yesworkflow.db.jooq.tables.Channel;
import org.yesworkflow.db.jooq.tables.Data;
import org.yesworkflow.db.jooq.tables.DataResource;
import org.yesworkflow.db.jooq.tables.Port;
import org.yesworkflow.db.jooq.tables.Program;
import org.yesworkflow.db.jooq.tables.Resource;
import org.yesworkflow.db.jooq.tables.SourceFile;
import org.yesworkflow.db.jooq.tables.UriVariable;
import org.yesworkflow.db.jooq.tables.UriVariableValue;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

	private static final long serialVersionUID = 812071789;

	/**
	 * The reference instance of <code></code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Annotation.ANNOTATION,
			Channel.CHANNEL,
			Data.DATA,
			DataResource.DATA_RESOURCE,
			Port.PORT,
			Program.PROGRAM,
			Resource.RESOURCE,
			SourceFile.SOURCE_FILE,
			UriVariable.URI_VARIABLE,
			UriVariableValue.URI_VARIABLE_VALUE);
	}
}
