/**
 * This class is generated by jOOQ
 */
package org.yesworkflow.db.jooq;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.yesworkflow.db.jooq.tables.Annotation;
import org.yesworkflow.db.jooq.tables.Channel;
import org.yesworkflow.db.jooq.tables.Data;
import org.yesworkflow.db.jooq.tables.DataResource;
import org.yesworkflow.db.jooq.tables.Port;
import org.yesworkflow.db.jooq.tables.Program;
import org.yesworkflow.db.jooq.tables.Resource;
import org.yesworkflow.db.jooq.tables.SourceFile;
import org.yesworkflow.db.jooq.tables.UriVariable;
import org.yesworkflow.db.jooq.tables.UriVariableValue;
import org.yesworkflow.db.jooq.tables.records.AnnotationRecord;
import org.yesworkflow.db.jooq.tables.records.ChannelRecord;
import org.yesworkflow.db.jooq.tables.records.DataRecord;
import org.yesworkflow.db.jooq.tables.records.DataResourceRecord;
import org.yesworkflow.db.jooq.tables.records.PortRecord;
import org.yesworkflow.db.jooq.tables.records.ProgramRecord;
import org.yesworkflow.db.jooq.tables.records.ResourceRecord;
import org.yesworkflow.db.jooq.tables.records.SourceFileRecord;
import org.yesworkflow.db.jooq.tables.records.UriVariableRecord;
import org.yesworkflow.db.jooq.tables.records.UriVariableValueRecord;


/**
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AnnotationRecord> PK_ANNOTATION = UniqueKeys0.PK_ANNOTATION;
	public static final UniqueKey<ChannelRecord> PK_CHANNEL = UniqueKeys0.PK_CHANNEL;
	public static final UniqueKey<DataRecord> PK_DATA = UniqueKeys0.PK_DATA;
	public static final UniqueKey<PortRecord> PK_PORT = UniqueKeys0.PK_PORT;
	public static final UniqueKey<ProgramRecord> PK_PROGRAM = UniqueKeys0.PK_PROGRAM;
	public static final UniqueKey<ResourceRecord> PK_RESOURCE = UniqueKeys0.PK_RESOURCE;
	public static final UniqueKey<SourceFileRecord> PK_SOURCE_FILE = UniqueKeys0.PK_SOURCE_FILE;
	public static final UniqueKey<UriVariableRecord> PK_URI_VARIABLE = UniqueKeys0.PK_URI_VARIABLE;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<AnnotationRecord, SourceFileRecord> FK_ANNOTATION_SOURCE_FILE_1 = ForeignKeys0.FK_ANNOTATION_SOURCE_FILE_1;
	public static final ForeignKey<AnnotationRecord, AnnotationRecord> FK_ANNOTATION_ANNOTATION_1 = ForeignKeys0.FK_ANNOTATION_ANNOTATION_1;
	public static final ForeignKey<ChannelRecord, DataRecord> FK_CHANNEL_DATA_1 = ForeignKeys0.FK_CHANNEL_DATA_1;
	public static final ForeignKey<ChannelRecord, PortRecord> FK_CHANNEL_PORT_2 = ForeignKeys0.FK_CHANNEL_PORT_2;
	public static final ForeignKey<ChannelRecord, PortRecord> FK_CHANNEL_PORT_1 = ForeignKeys0.FK_CHANNEL_PORT_1;
	public static final ForeignKey<DataResourceRecord, DataRecord> FK_DATA_RESOURCE_DATA_1 = ForeignKeys0.FK_DATA_RESOURCE_DATA_1;
	public static final ForeignKey<DataResourceRecord, ResourceRecord> FK_DATA_RESOURCE_RESOURCE_1 = ForeignKeys0.FK_DATA_RESOURCE_RESOURCE_1;
	public static final ForeignKey<PortRecord, AnnotationRecord> FK_PORT_ANNOTATION_1 = ForeignKeys0.FK_PORT_ANNOTATION_1;
	public static final ForeignKey<PortRecord, ProgramRecord> FK_PORT_PROGRAM_1 = ForeignKeys0.FK_PORT_PROGRAM_1;
	public static final ForeignKey<PortRecord, DataRecord> FK_PORT_DATA_1 = ForeignKeys0.FK_PORT_DATA_1;
	public static final ForeignKey<ProgramRecord, ProgramRecord> FK_PROGRAM_PROGRAM_1 = ForeignKeys0.FK_PROGRAM_PROGRAM_1;
	public static final ForeignKey<ProgramRecord, AnnotationRecord> FK_PROGRAM_ANNOTATION_2 = ForeignKeys0.FK_PROGRAM_ANNOTATION_2;
	public static final ForeignKey<ProgramRecord, AnnotationRecord> FK_PROGRAM_ANNOTATION_1 = ForeignKeys0.FK_PROGRAM_ANNOTATION_1;
	public static final ForeignKey<UriVariableRecord, PortRecord> FK_URI_VARIABLE_PORT_1 = ForeignKeys0.FK_URI_VARIABLE_PORT_1;
	public static final ForeignKey<UriVariableValueRecord, UriVariableRecord> FK_URI_VARIABLE_VALUE_URI_VARIABLE_1 = ForeignKeys0.FK_URI_VARIABLE_VALUE_URI_VARIABLE_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AnnotationRecord> PK_ANNOTATION = createUniqueKey(Annotation.ANNOTATION, Annotation.ANNOTATION.ID);
		public static final UniqueKey<ChannelRecord> PK_CHANNEL = createUniqueKey(Channel.CHANNEL, Channel.CHANNEL.ID);
		public static final UniqueKey<DataRecord> PK_DATA = createUniqueKey(Data.DATA, Data.DATA.ID);
		public static final UniqueKey<PortRecord> PK_PORT = createUniqueKey(Port.PORT, Port.PORT.ID);
		public static final UniqueKey<ProgramRecord> PK_PROGRAM = createUniqueKey(Program.PROGRAM, Program.PROGRAM.ID);
		public static final UniqueKey<ResourceRecord> PK_RESOURCE = createUniqueKey(Resource.RESOURCE, Resource.RESOURCE.ID);
		public static final UniqueKey<SourceFileRecord> PK_SOURCE_FILE = createUniqueKey(SourceFile.SOURCE_FILE, SourceFile.SOURCE_FILE.ID);
		public static final UniqueKey<UriVariableRecord> PK_URI_VARIABLE = createUniqueKey(UriVariable.URI_VARIABLE, UriVariable.URI_VARIABLE.ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<AnnotationRecord, SourceFileRecord> FK_ANNOTATION_SOURCE_FILE_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_SOURCE_FILE, Annotation.ANNOTATION, Annotation.ANNOTATION.SOURCE_FILE_ID);
		public static final ForeignKey<AnnotationRecord, AnnotationRecord> FK_ANNOTATION_ANNOTATION_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_ANNOTATION, Annotation.ANNOTATION, Annotation.ANNOTATION.QUALIFIES);
		public static final ForeignKey<ChannelRecord, DataRecord> FK_CHANNEL_DATA_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_DATA, Channel.CHANNEL, Channel.CHANNEL.DATA_ID);
		public static final ForeignKey<ChannelRecord, PortRecord> FK_CHANNEL_PORT_2 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_PORT, Channel.CHANNEL, Channel.CHANNEL.OUT_PORT_ID);
		public static final ForeignKey<ChannelRecord, PortRecord> FK_CHANNEL_PORT_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_PORT, Channel.CHANNEL, Channel.CHANNEL.IN_PORT_ID);
		public static final ForeignKey<DataResourceRecord, DataRecord> FK_DATA_RESOURCE_DATA_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_DATA, DataResource.DATA_RESOURCE, DataResource.DATA_RESOURCE.DATA_ID);
		public static final ForeignKey<DataResourceRecord, ResourceRecord> FK_DATA_RESOURCE_RESOURCE_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_RESOURCE, DataResource.DATA_RESOURCE, DataResource.DATA_RESOURCE.RESOURCE_ID);
		public static final ForeignKey<PortRecord, AnnotationRecord> FK_PORT_ANNOTATION_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_ANNOTATION, Port.PORT, Port.PORT.ANNOTATION_ID);
		public static final ForeignKey<PortRecord, ProgramRecord> FK_PORT_PROGRAM_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_PROGRAM, Port.PORT, Port.PORT.PROGRAM_ID);
		public static final ForeignKey<PortRecord, DataRecord> FK_PORT_DATA_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_DATA, Port.PORT, Port.PORT.DATA_ID);
		public static final ForeignKey<ProgramRecord, ProgramRecord> FK_PROGRAM_PROGRAM_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_PROGRAM, Program.PROGRAM, Program.PROGRAM.PARENT_ID);
		public static final ForeignKey<ProgramRecord, AnnotationRecord> FK_PROGRAM_ANNOTATION_2 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_ANNOTATION, Program.PROGRAM, Program.PROGRAM.BEGIN_ID);
		public static final ForeignKey<ProgramRecord, AnnotationRecord> FK_PROGRAM_ANNOTATION_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_ANNOTATION, Program.PROGRAM, Program.PROGRAM.END_ID);
		public static final ForeignKey<UriVariableRecord, PortRecord> FK_URI_VARIABLE_PORT_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_PORT, UriVariable.URI_VARIABLE, UriVariable.URI_VARIABLE.PORT_ID);
		public static final ForeignKey<UriVariableValueRecord, UriVariableRecord> FK_URI_VARIABLE_VALUE_URI_VARIABLE_1 = createForeignKey(org.yesworkflow.db.jooq.Keys.PK_URI_VARIABLE, UriVariableValue.URI_VARIABLE_VALUE, UriVariableValue.URI_VARIABLE_VALUE.URI_VARIABLE_ID);
	}
}
