/**
 * This class is generated by jOOQ
 */
package org.yesworkflow.db.jooq;


import javax.annotation.Generated;

import org.yesworkflow.db.jooq.tables.Annotation;
import org.yesworkflow.db.jooq.tables.Channel;
import org.yesworkflow.db.jooq.tables.Data;
import org.yesworkflow.db.jooq.tables.DataResource;
import org.yesworkflow.db.jooq.tables.Port;
import org.yesworkflow.db.jooq.tables.Program;
import org.yesworkflow.db.jooq.tables.Resource;
import org.yesworkflow.db.jooq.tables.SourceFile;
import org.yesworkflow.db.jooq.tables.UriVariable;
import org.yesworkflow.db.jooq.tables.UriVariableValue;


/**
 * Convenience access to all tables in 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table annotation
	 */
	public static final Annotation ANNOTATION = org.yesworkflow.db.jooq.tables.Annotation.ANNOTATION;

	/**
	 * The table channel
	 */
	public static final Channel CHANNEL = org.yesworkflow.db.jooq.tables.Channel.CHANNEL;

	/**
	 * The table data
	 */
	public static final Data DATA = org.yesworkflow.db.jooq.tables.Data.DATA;

	/**
	 * The table data_resource
	 */
	public static final DataResource DATA_RESOURCE = org.yesworkflow.db.jooq.tables.DataResource.DATA_RESOURCE;

	/**
	 * The table port
	 */
	public static final Port PORT = org.yesworkflow.db.jooq.tables.Port.PORT;

	/**
	 * The table program
	 */
	public static final Program PROGRAM = org.yesworkflow.db.jooq.tables.Program.PROGRAM;

	/**
	 * The table resource
	 */
	public static final Resource RESOURCE = org.yesworkflow.db.jooq.tables.Resource.RESOURCE;

	/**
	 * The table source_file
	 */
	public static final SourceFile SOURCE_FILE = org.yesworkflow.db.jooq.tables.SourceFile.SOURCE_FILE;

	/**
	 * The table uri_variable
	 */
	public static final UriVariable URI_VARIABLE = org.yesworkflow.db.jooq.tables.UriVariable.URI_VARIABLE;

	/**
	 * The table uri_variable_value
	 */
	public static final UriVariableValue URI_VARIABLE_VALUE = org.yesworkflow.db.jooq.tables.UriVariableValue.URI_VARIABLE_VALUE;
}
