
YW_DIST_BASE = ../..
TOOLS_DIR = $(YW_DIST_BASE)/tools
RULES_DIR = $(TOOLS_DIR)/rules
SCRIPTS_DIR = $(TOOLS_DIR)/scripts
MAKEFILES_DIR = $(TOOLS_DIR)/makefiles

OUTPUT_DIR = ./
FACTS_DIR = $(OUTPUT_DIR)/facts
GRAPHS_DIR = $(OUTPUT_DIR)/graphs
