/**
 * This class is generated by jOOQ
 */
package org.yesworkflow.db.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.yesworkflow.db.jooq.DefaultSchema;
import org.yesworkflow.db.jooq.Keys;
import org.yesworkflow.db.jooq.tables.records.SourceFileRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceFile extends TableImpl<SourceFileRecord> {

	private static final long serialVersionUID = -1888001553;

	/**
	 * The reference instance of <code>source_file</code>
	 */
	public static final SourceFile SOURCE_FILE = new SourceFile();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SourceFileRecord> getRecordType() {
		return SourceFileRecord.class;
	}

	/**
	 * The column <code>source_file.id</code>.
	 */
	public final TableField<SourceFileRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>source_file.path</code>.
	 */
	public final TableField<SourceFileRecord, String> PATH = createField("path", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>source_file</code> table reference
	 */
	public SourceFile() {
		this("source_file", null);
	}

	/**
	 * Create an aliased <code>source_file</code> table reference
	 */
	public SourceFile(String alias) {
		this(alias, SOURCE_FILE);
	}

	private SourceFile(String alias, Table<SourceFileRecord> aliased) {
		this(alias, aliased, null);
	}

	private SourceFile(String alias, Table<SourceFileRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SourceFileRecord> getPrimaryKey() {
		return Keys.PK_SOURCE_FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SourceFileRecord>> getKeys() {
		return Arrays.<UniqueKey<SourceFileRecord>>asList(Keys.PK_SOURCE_FILE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceFile as(String alias) {
		return new SourceFile(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SourceFile rename(String name) {
		return new SourceFile(name, null);
	}
}
