/**
 * This class is generated by jOOQ
 */
package org.yesworkflow.db.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.yesworkflow.db.jooq.DefaultSchema;
import org.yesworkflow.db.jooq.Keys;
import org.yesworkflow.db.jooq.tables.records.UriVariableValueRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UriVariableValue extends TableImpl<UriVariableValueRecord> {

	private static final long serialVersionUID = 617357911;

	/**
	 * The reference instance of <code>uri_variable_value</code>
	 */
	public static final UriVariableValue URI_VARIABLE_VALUE = new UriVariableValue();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UriVariableValueRecord> getRecordType() {
		return UriVariableValueRecord.class;
	}

	/**
	 * The column <code>uri_variable_value.resource_id</code>.
	 */
	public final TableField<UriVariableValueRecord, Integer> RESOURCE_ID = createField("resource_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>uri_variable_value.uri_variable_id</code>.
	 */
	public final TableField<UriVariableValueRecord, Integer> URI_VARIABLE_ID = createField("uri_variable_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>uri_variable_value.value</code>.
	 */
	public final TableField<UriVariableValueRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>uri_variable_value</code> table reference
	 */
	public UriVariableValue() {
		this("uri_variable_value", null);
	}

	/**
	 * Create an aliased <code>uri_variable_value</code> table reference
	 */
	public UriVariableValue(String alias) {
		this(alias, URI_VARIABLE_VALUE);
	}

	private UriVariableValue(String alias, Table<UriVariableValueRecord> aliased) {
		this(alias, aliased, null);
	}

	private UriVariableValue(String alias, Table<UriVariableValueRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<UriVariableValueRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<UriVariableValueRecord, ?>>asList(Keys.FK_URI_VARIABLE_VALUE_URI_VARIABLE_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UriVariableValue as(String alias) {
		return new UriVariableValue(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UriVariableValue rename(String name) {
		return new UriVariableValue(name, null);
	}
}
